language: php
php:
  - 7.3
  - 7.4
before_install:
  - nvm install --latest-npm
  - phpenv config-rm xdebug.ini # Disable XDebug to speed up PHP builds
install:
  - composer install --no-interaction --prefer-dist
  - npm install
script:
  - composer run test
  - composer run codestyle
  - npm run lint
cache:
  npm: true
  directories:
    - $HOME/.composer/cache
