language: php
install:
  - phpenv config-rm xdebug.ini # Disable XDebug to speed up PHP builds
  - composer install --no-interaction --prefer-dist
script:
  - composer run test
  - composer run codestyle
jobs:
  include:
    - php: 7.3
    - php: 7.4
    - language: node_js
      node_js: 12
      install: npm install
      script: npm run lint
cache:
  npm: true
  directories:
    - $HOME/.composer/cache
